INSERT INTO alias (alias_name) VALUES
('The Conqueror'),   
('The Dreamer'),    
('The Glorious'), 
('The Cruel'),            
('The Uncrowned'),      
('The Old King'),     
('The Conciliator'), 
('The Good Queen'),  
('The Queen Who Never Was'),
('The Rogue Prince'), 
('The Realm’s Delight'),  
('The Dragonbane'),     
('The Young Dragon'),   
('The Blessed'),        
('The Defiant'),        
('The Unworthy'),    
('The Dragonknight'),     
('Breakspear'),           
('Brightflame'),         
('The Unlikely'),         
('The Mad King'),         
('The Silver Prince'),     
('The Beggar King'),       
('Stormborn'),             
('Mother of Dragons'),     
('The Bastard of Winterfell');