INSERT INTO targaryen_alias (targaryen_id, alias_id) VALUES
((SELECT character_id FROM targaryen WHERE full_name = 'Aegon Targaryen I'), (SELECT alias_id FROM alias WHERE alias_name = 'The Conqueror')),
((SELECT character_id FROM targaryen WHERE full_name = 'Daenys Targaryen'), (SELECT alias_id FROM alias WHERE alias_name = 'The Dreamer')),
((SELECT character_id FROM targaryen WHERE full_name = 'Gaemon Targaryen'), (SELECT alias_id FROM alias WHERE alias_name = 'The Glorious')),
((SELECT character_id FROM targaryen WHERE full_name = 'Maegor Targaryen I'), (SELECT alias_id FROM alias WHERE alias_name = 'The Cruel')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aegon Targaryen (the Uncrowned)'), (SELECT alias_id FROM alias WHERE alias_name = 'The Uncrowned')),
((SELECT character_id FROM targaryen WHERE full_name = 'Jaehaerys Targaryen I'), (SELECT alias_id FROM alias WHERE alias_name = 'The Old King')),
((SELECT character_id FROM targaryen WHERE full_name = 'Jaehaerys Targaryen I'), (SELECT alias_id FROM alias WHERE alias_name = 'The Conciliator')),
((SELECT character_id FROM targaryen WHERE full_name = 'Alysanne Targaryen'), (SELECT alias_id FROM alias WHERE alias_name = 'The Good Queen')),
((SELECT character_id FROM targaryen WHERE full_name = 'Rhaenys Targaryen (daughter of Aemon)'), (SELECT alias_id FROM alias WHERE alias_name = 'The Queen Who Never Was')),
((SELECT character_id FROM targaryen WHERE full_name = 'Daemon Targaryen'), (SELECT alias_id FROM alias WHERE alias_name = 'The Rogue Prince')),
((SELECT character_id FROM targaryen WHERE full_name = 'Rhaenyra Targaryen'), (SELECT alias_id FROM alias WHERE alias_name = 'The Realm’s Delight')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aegon Targaryen III'), (SELECT alias_id FROM alias WHERE alias_name = 'The Dragonbane')),
((SELECT character_id FROM targaryen WHERE full_name = 'Daeron Targaryen I'), (SELECT alias_id FROM alias WHERE alias_name = 'The Young Dragon')),
((SELECT character_id FROM targaryen WHERE full_name = 'Baelor Targaryen I'), (SELECT alias_id FROM alias WHERE alias_name = 'The Blessed')),
((SELECT character_id FROM targaryen WHERE full_name = 'Daena Targaryen'), (SELECT alias_id FROM alias WHERE alias_name = 'The Defiant')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aegon Targaryen IV'), (SELECT alias_id FROM alias WHERE alias_name = 'The Unworthy')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aemon the Dragonknight'), (SELECT alias_id FROM alias WHERE alias_name = 'The Dragonknight')),
((SELECT character_id FROM targaryen WHERE full_name = 'Baelor Breakspear'), (SELECT alias_id FROM alias WHERE alias_name = 'Breakspear')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aerion Targaryen (Brightflame)'), (SELECT alias_id FROM alias WHERE alias_name = 'Brightflame')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aegon Targaryen V'), (SELECT alias_id FROM alias WHERE alias_name = 'The Unlikely')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aerys Targaryen II'), (SELECT alias_id FROM alias WHERE alias_name = 'The Mad King')),
((SELECT character_id FROM targaryen WHERE full_name = 'Rhaegar Targaryen'), (SELECT alias_id FROM alias WHERE alias_name = 'The Silver Prince')),
((SELECT character_id FROM targaryen WHERE full_name = 'Viserys Targaryen'), (SELECT alias_id FROM alias WHERE alias_name = 'The Beggar King')),
((SELECT character_id FROM targaryen WHERE full_name = 'Daenerys Targaryen'), (SELECT alias_id FROM alias WHERE alias_name = 'Stormborn')),
((SELECT character_id FROM targaryen WHERE full_name = 'Daenerys Targaryen'), (SELECT alias_id FROM alias WHERE alias_name = 'Mother of Dragons')),
((SELECT character_id FROM targaryen WHERE full_name = 'Jon Snow (Aegon Targaryen)'), (SELECT alias_id FROM alias WHERE alias_name = 'The Bastard of Winterfell'));