INSERT INTO targaryen_title (targaryen_id, title_id) VALUES
-- kings
((SELECT character_id FROM targaryen WHERE full_name = 'Aegon Targaryen I'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aenys Targaryen I'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Maegor Targaryen I'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Jaehaerys Targaryen I'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Viserys Targaryen I'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aegon Targaryen II'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aegon Targaryen III'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Daeron Targaryen I'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Baelor Targaryen I'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Viserys Targaryen II'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aegon Targaryen IV'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Daeron Targaryen II'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aerys Targaryen I'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Maekar Targaryen I'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aegon Targaryen V'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Jaehaerys Targaryen II'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aerys Targaryen II'), (SELECT title_id FROM title WHERE title_name = 'King of the Seven Kingdoms')),
-- queens consort
((SELECT character_id FROM targaryen WHERE full_name = 'Visenya Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Queen Consort')),
((SELECT character_id FROM targaryen WHERE full_name = 'Rhaenys Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Queen Consort')),
((SELECT character_id FROM targaryen WHERE full_name = 'Alysanne Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Queen Consort')),
((SELECT character_id FROM targaryen WHERE full_name = 'Helaena Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Queen Consort')),
((SELECT character_id FROM targaryen WHERE full_name = 'Naerys Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Queen Consort')),
((SELECT character_id FROM targaryen WHERE full_name = 'Rhaella Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Queen Consort')),
-- queen regnant
((SELECT character_id FROM targaryen WHERE full_name = 'Rhaenyra Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Queen Regnant')),
-- lords/ladies of dragonstone
((SELECT character_id FROM targaryen WHERE full_name = 'Aenar Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Lord of Dragonstone')),
((SELECT character_id FROM targaryen WHERE full_name = 'Gaemon Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Lord of Dragonstone')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aegon Targaryen (son of Gaemon)'), (SELECT title_id FROM title WHERE title_name = 'Lord of Dragonstone')),
((SELECT character_id FROM targaryen WHERE full_name = 'Maegon Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Lord of Dragonstone')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aerys Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Lord of Dragonstone')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aelyx Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Lord of Dragonstone')),
((SELECT character_id FROM targaryen WHERE full_name = 'Baelon Targaryen (son of Aerys)'), (SELECT title_id FROM title WHERE title_name = 'Lord of Dragonstone')),
((SELECT character_id FROM targaryen WHERE full_name = 'Daemion Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Lord of Dragonstone')),
((SELECT character_id FROM targaryen WHERE full_name = 'Aerion Targaryen (pre-conquest)'), (SELECT title_id FROM title WHERE title_name = 'Lord of Dragonstone')),
((SELECT character_id FROM targaryen WHERE full_name = 'Elaena Targaryen (pre-conquest)'), (SELECT title_id FROM title WHERE title_name = 'Lady of Dragonstone')),
((SELECT character_id FROM targaryen WHERE full_name = 'Daenys Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Lady of Dragonstone')),
-- princes/princesses
((SELECT character_id FROM targaryen WHERE full_name = 'Rhaegar Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Prince of Dragonstone')),
((SELECT character_id FROM targaryen WHERE full_name = 'Rhaenys Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Princess')),
((SELECT character_id FROM targaryen WHERE full_name = 'Visenya Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Princess')),
((SELECT character_id FROM targaryen WHERE full_name = 'Rhaenys Targaryen (daughter of Aemon)'), (SELECT title_id FROM title WHERE title_name = 'Princess')),
((SELECT character_id FROM targaryen WHERE full_name = 'Daemon Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Prince')),
((SELECT character_id FROM targaryen WHERE full_name = 'Baela Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Princess')),
((SELECT character_id FROM targaryen WHERE full_name = 'Rhaena Targaryen (daughter of Daemon)'), (SELECT title_id FROM title WHERE title_name = 'Princess')),
((SELECT character_id FROM targaryen WHERE full_name = 'Daenerys Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Princess')),
((SELECT character_id FROM targaryen WHERE full_name = 'Viserys Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Prince')),
-- special roles
((SELECT character_id FROM targaryen WHERE full_name = 'Aemon Targaryen (Maester)'), (SELECT title_id FROM title WHERE title_name = 'Maester')),
((SELECT character_id FROM targaryen WHERE full_name = 'Maegelle Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Septa')),
((SELECT character_id FROM targaryen WHERE full_name = 'Vaegon Targaryen'), (SELECT title_id FROM title WHERE title_name = 'Archmaester'));